import express from 'express';
import {
    createCakeDesign,

} from '../controllers/cakeDesign.controller.js';
import { verifyToken } from '../middleware/verifyUser.js';
const router = express.Router();

/**
 * @swagger
 * /api/cake-designs/create:
 *   post:
 *     tags:
 *       - Cake Design
 *     summary: Create a new cake design
 *     description: Create a new cake design with user association
 *     security:
 *       - bearerAuth: []
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             required:
 *               - user_id
 *               - design_image
 *             properties:
 *               user_id:
 *                 type: integer
 *                 description: ID of the user creating the design
 *                 example: 1
 *               description:
 *                 type: string
 *                 description: Description of the cake design
 *                 example: "A beautiful chocolate cake with vanilla frosting and sprinkles"
 *                 nullable: true
 *               design_image:
 *                 type: string
 *                 description: URL or base64 string of the design image
 *                 example: "https://example.com/cake-design.jpg"
 *               is_public:
 *                 type: boolean
 *                 description: Whether the design is public or private
 *                 default: true
 *                 example: true
 *               is_ai_generated:
 *                 type: boolean
 *                 description: Whether the design was generated by AI
 *                 default: false
 *                 example: false
 *     responses:
 *       201:
 *         description: Cake design created successfully
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: true
 *                 message:
 *                   type: string
 *                   example: "Cake design created successfully"
 *                 data:
 *                   type: object
 *                   properties:
 *                     id:
 *                       type: integer
 *                       example: 1
 *                     user_id:
 *                       type: integer
 *                       example: 1
 *                     description:
 *                       type: string
 *                       nullable: true
 *                       example: "A beautiful chocolate cake with vanilla frosting and sprinkles"
 *                     design_image:
 *                       type: string
 *                       example: "https://example.com/cake-design.jpg"
 *                     created_at:
 *                       type: string
 *                       format: date-time
 *                       example: "2024-01-15T10:30:00.000Z"
 *                     is_public:
 *                       type: boolean
 *                       example: true
 *                     is_ai_generated:
 *                       type: boolean
 *                       example: false
 *       400:
 *         description: Bad Request - Missing required fields
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "user_id and design_image are required"
 *       404:
 *         description: Not Found - User not found
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "User not found"
 *       401:
 *         description: Unauthorized - Invalid or missing token
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "Access denied. No token provided."
 *       500:
 *         description: Internal Server Error
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 success:
 *                   type: boolean
 *                   example: false
 *                 message:
 *                   type: string
 *                   example: "Internal server error"
 *                 error:
 *                   type: string
 *                   example: "Database connection error"
 */
router.post('/create', verifyToken, createCakeDesign);


export default router;